releases:
  latest:
    release:
      channel: stable
      version: "4.4"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- artifact_dir: /tmp/artifacts
  as: cvp-common-aws
  cron: '@yearly'
  steps:
    cluster_profile: aws-cpaas
    workflow: optional-operators-cvp-common-aws
zz_generated_metadata:
  branch: cvp-ocp-4.4
  org: redhat-operator-ecosystem
  repo: playground
